config:
  jwt:
    secret: '2159cslsknjgvehr'
    expire: '86400'                             # 24 * 60 * 60
    header: 'Authorization'
  redis:
    default-expire: '86400'                     # 24 * 60 * 60
    not-expire: '86400'                         # 24 * 60 * 60