spring:
  profiles:
    active: dev # 配置环境

server:
  port: 8081
  servlet:
    context-path: /api

# 自定义配置
config:
  weixin:
    appid: wx25adff2e6b2572ed
    secret: wx25adff2e6b2572edwx25adff2e6b25
