spring:
  profiles:
    active: dev # 配置环境

server:
  port: 8082 # 配置端口
  servlet:
    context-path: /api # 配置接口前缀

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zxiaosi.common.entity
  configuration:
    map-underscore-to-camel-case: true # 大小写转换

# 自定义配置
config:
  weixin:
    appid: wx25adff2e6b2572ed
    secret: wx25adff2e6b2572edwx25adff2e6b25
