spring:
  datasource:
    url: jdbc:mysql://mysql:3306/stack?useUnicode=true&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    port: 6379
    host: redis
    password: 123456
    database: 1

# 自定义配置
config:
  domain: https://zxiaosi.cn